=== MeRPG/influence/influence-android/assets/font/fontsSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="font">

        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="scalexy" type="xs:float" use="optional"/>
        <xs:attribute name="scalex" type="xs:float" use="optional"/>
        <xs:attribute name="scaley" type="xs:float" use="optional"/>
        <xs:attribute name="bitmap" type="xs:string" use="optional"/>

    </xs:complexType>

    <xs:complexType name="fonts">
        <xs:sequence maxOccurs="unbounded" minOccurs="0" >
            <xs:element name="font" type="font" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="fonts" type="fonts"/>

</xs:schema>

=== MeRPG/influence/influence-android/assets/font/fonts.xml
<?xml version="1.0"  standalone="no"?>
<fonts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fontsSchema.xsd">
    <font name="status" bitmap="statusFont" scalexy="0.87" />
    <font name="substatus" bitmap="substatusFont"/>
    <font name="cells" bitmap="cellsFont"/>
    <font name="debug" scalexy="0.9" bitmap="substatusFont"/>
    <font name="popup" scalexy="0.9" bitmap="statusFont"/>
    <font name="title" bitmap="statusFont"/>
    <font name="label" bitmap="substatusFont"/>
</fonts>
