=== MeRPG/influence/defaultDir/.influence/misc/matchSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="language" xml:base="xs:string">
        <xs:restriction>
            <xs:enumeration value="en" />
            <xs:enumeration value="ru" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="players">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="2"/>
            <xs:maxInclusive value="8"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="playerTypes">
        <xs:restriction base="xs:string" >
            <xs:enumeration value="Dummy" />
            <xs:enumeration value="Beefy" />
            <xs:enumeration value="Lazy" />
            <xs:enumeration value="Smarty" />
            <xs:enumeration value="Random" />
            <xs:enumeration value="Hunter" />
            <xs:enumeration value="Human" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="player">
        <xs:simpleContent>
            <xs:extension base="playerTypes">
                <xs:attribute name="number" type="xs:int" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="playersTop">
        <xs:sequence>
            <xs:element name="player" type="player" minOccurs="2" maxOccurs="8" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="difficulty" xml:base="xs:string">
        <xs:restriction>
            <xs:enumeration value="EASY" />
            <xs:enumeration value="NORMAL" />
            <xs:enumeration value="HARD" />
            <xs:enumeration value="INSANE" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fieldSize" xml:base="xs:string">
        <xs:restriction>
            <xs:enumeration value="SMALL" />
            <xs:enumeration value="NORMAL" />
            <xs:enumeration value="LARGE" />
            <xs:enumeration value="XLARGE" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="game">
        <xs:sequence>
            <xs:element name="players" type="players" />
            <xs:element name="difficulty" type="difficulty" />
            <xs:element name="fieldSize" type="fieldSize" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="cellPower">
        <xs:restriction>
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="12" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cell">
        <xs:simpleContent>
            <xs:extension base="cellPower">
                <xs:attribute name="number" type="xs:int" />
                <xs:attribute name="unitsX" type="xs:int" />
                <xs:attribute name="unitsY" type="xs:int" />
                <xs:attribute name="maxPower" type="xs:int" />
                <xs:attribute name="type" type="xs:int" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="route">
        <xs:simpleContent>
            <xs:extension base="cellPower">
                <xs:attribute name="from" type="xs:int" />
                <xs:attribute name="to" type="xs:int" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="field">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="cell" type="cell" />
            <xs:element name="route" type="route" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="match">
        <xs:sequence>
            <xs:element name="players" type="playersTop" />
            <xs:element name="game" type="game" />
            <xs:element name="field" type="field" />
        </xs:sequence>
    </xs:complexType>


    <xs:element name="match" type="match" />

</xs:schema>

=== MeRPG/influence/defaultDir/.influence/match.xml
<?xml version="1.0"  standalone="no"?>
<match xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="misc/matchSchema.xsd">
	<players>
		<player number="0">Human</player>
		<player number="1">Dummy</player>
		<player number="2">Dummy</player>
		<player number="3">Dummy</player>
		<player number="4">Dummy</player>
	</players>
	<game>
		<players>5</players>
		<difficulty>NORMAL</difficulty>
		<fieldSize>NORMAL</fieldSize>
	</game>
	<field>
		<cell number="1" unitsX="0" unitsY="1" maxPower="8" type="0">2</cell>
		<cell number="2" unitsX="0" unitsY="2" maxPower="8" type="-1">0</cell>
		<cell number="3" unitsX="0" unitsY="3" maxPower="8" type="-1">0</cell>
		<cell number="4" unitsX="0" unitsY="4" maxPower="12" type="-1">0</cell>
		<cell number="5" unitsX="1" unitsY="0" maxPower="12" type="-1">0</cell>
		<cell number="6" unitsX="1" unitsY="1" maxPower="12" type="-1">0</cell>
		<cell number="7" unitsX="1" unitsY="2" maxPower="8" type="3">2</cell>
		<cell number="8" unitsX="1" unitsY="3" maxPower="12" type="-1">0</cell>
		<cell number="10" unitsX="2" unitsY="0" maxPower="12" type="1">2</cell>
		<cell number="11" unitsX="2" unitsY="1" maxPower="8" type="-1">0</cell>
		<cell number="12" unitsX="2" unitsY="2" maxPower="8" type="-1">0</cell>
		<cell number="13" unitsX="2" unitsY="3" maxPower="8" type="-1">0</cell>
		<cell number="15" unitsX="3" unitsY="0" maxPower="8" type="-1">0</cell>
		<cell number="16" unitsX="3" unitsY="1" maxPower="12" type="4">2</cell>
		<cell number="17" unitsX="3" unitsY="2" maxPower="12" type="-1">0</cell>
		<cell number="20" unitsX="4" unitsY="0" maxPower="8" type="-1">0</cell>
		<cell number="23" unitsX="4" unitsY="3" maxPower="12" type="-1">0</cell>
		<cell number="24" unitsX="4" unitsY="4" maxPower="12" type="-1">0</cell>
		<cell number="26" unitsX="5" unitsY="1" maxPower="8" type="-1">0</cell>
		<cell number="27" unitsX="5" unitsY="2" maxPower="8" type="2">2</cell>
		<cell number="28" unitsX="5" unitsY="3" maxPower="12" type="-1">0</cell>
		<cell number="31" unitsX="6" unitsY="1" maxPower="8" type="-1">0</cell>
		<cell number="32" unitsX="6" unitsY="2" maxPower="8" type="-1">0</cell>
		<cell number="33" unitsX="6" unitsY="3" maxPower="8" type="-1">0</cell>
		<cell number="34" unitsX="6" unitsY="4" maxPower="8" type="-1">0</cell>
        <routes></routes>
	</field>
</match>
