=== MeRPG/influence/influence-android/assets/ui/screenSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="element">

        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="region" type="xs:string" use="required"/>
        <xs:attribute name="secondRegion" type="xs:string" use="optional"/>
        <xs:attribute name="localized" type="xs:boolean" use="required"/>
        <xs:attribute name="x" type="xs:int" use="required"/>
        <xs:attribute name="y" type="xs:int" use="required"/>

    </xs:complexType>

    <xs:complexType name="screen">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element name="element" type="element" />
        </xs:sequence>
        <xs:attribute name="atlas" type="xs:string" use="required"/>
        <xs:attribute name="localized" type="xs:boolean" use="required"/>
        <xs:attribute name="defaultBackground" type="xs:boolean" use="optional" default="false"/>
    </xs:complexType>


    <xs:element name="screen" type="screen"/>

</xs:schema>

=== MeRPG/influence/influence-android/assets/ui/players.xml
<?xml version="1.0"  standalone="no"?>
<screen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="screenSchema.xsd"
        atlas="players" localized="false" defaultBackground="true">
	<element name="easy" region="easy_Active" secondRegion="easy_noActive" localized="true"
				x="24" y="465"/>
	<element name="normal" region="normal_Active" secondRegion="normal_noActive" localized="true"
				x="24" y="421"/>	
	<element name="hard" region="hard_Active" secondRegion="hard_noActive" localized="true"
				x="240" y="465"/>
	<element name="custom" region="custom_Active" secondRegion="custom_noActive" localized="true"
				x="240" y="421"/>
	<element name="green" region="enemiesGreen" localized="false"
				x="92" y="322"/>	
	<element name="yellow" region="enemiesYellow" localized="false"
				x="92" y="272"/>	
	<element name="red" region="enemiesRed" localized="false"
				x="92" y="222"/>	
	<element name="purple" region="enemiesPurpure" localized="false"
				x="92" y="172"/>
	<element name="delete" region="buttonDelete" localized="false"
				x="399" y="177"/>
	<element name="start" region="buttonStart" localized="true"
				x="143" y="85"/>
    <element name="Human" region="human" localized="true"
             x="191" y="-100"/>
    <element name="Smarty" region="smarty" localized="true"
				x="92" y="-100"/>
	<element name="Dummy" region="dummy" localized="true"
				x="92" y="-100"/>
	<element name="Hunter" region="hunter" localized="true"
				x="92" y="-100"/>
	<element name="Lazy" region="lazy" localized="true"
				x="92" y="-100"/>
    <element name="Beefy" region="beefy" localized="true"
             x="92" y="-100"/>
    <element name="Random" region="freak" localized="true"
             x="92" y="-100"/>
    <element name="add" region="enemiesAdd" localized="true"
             x="92" y="222"/>
    <element name="startgameText" region="startgameText" localized="true"
             x="89" y="605"/>
    <label font="substatusFont" color="ffffff" x="240" y="403" localized="true" align="CENTER" >enemies</label>
    <label font="substatusFont" color="ffffff" x="240" y="550" localized="true" align="CENTER" >difficulty</label>
</screen>

=== MeRPG/influence/influence-android/assets/ui/settingsScreen.xml
<?xml version="1.0"  standalone="no"?>
<screen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="screenSchema.xsd"
        atlas="settings" localized="false" defaultBackground="true">
    <element name="sounds" region="soundOn" secondRegion="soundOff" localized="false"
            x="79" y="377"/>
    <element name="vibrate" region="vibrationOn" secondRegion="vibrationOff" localized="false"
            x="265" y="372"/>
    <element name="ru" region="languageRussianOn" secondRegion="languageRussianOff" localized="false"
            x="73" y="231"/>
    <element name="en" region="languageEnglishOn" secondRegion="languageEnglishOff" localized="false"
            x="236" y="231"/>
    <element name="slow" region="speedSlowOn" secondRegion="speedSlowOff" localized="true"
            x="0" y="84"/>
    <element name="normal" region="speedNormalOn" secondRegion="speedNormalOff" localized="true"
            x="138" y="84"/>
    <element name="fast" region="speedFastOn" secondRegion="speedFastOff" localized="true"
            x="312" y="84"/>
    <element name="settingsText" region="settingsText" localized="true"
             x="108" y="605"/>
</screen>

=== MeRPG/influence/defaultDir/.influence/ui/settingsScreen.xml
<?xml version="1.0"  standalone="no"?>
<screen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="screenSchema.xsd"
        atlas="settingsScreen" localized="true">
    <element name="sounds" region="soundOn" secondRegion="soundOff" localized="false"
            x="15" y="296"/>
    <element name="vibrate" region="vibrationOn" secondRegion="vibrationOff" localized="false"
            x="15" y="296"/>
    <element name="ru" region="languageRussianOn" secondRegion="languageRussianOff" localized="false"
            x="15" y="296"/>
    <element name="en" region="languageEnglishOn" secondRegion="languageEnglishOff" localized="false"
            x="15" y="296"/>
    <element name="slow" region="speedSlowOn" secondRegion="speedSlowOff" localized="false"
            x="15" y="296"/>
    <element name="normal" region="speedNormalOn" secondRegion="speedNormalOff" localized="false"
            x="15" y="296"/>
    <element name="fast" region="speedFastOn" secondRegion="speedFastOff" localized="false"
            x="15" y="296"/>    
	<element name="fast2" region="speedFastOn" localized="false"
            x="50" y="50"/>
	<element name="fast3" region="speedFastOff" localized="false"
            x="50" y="50"/>
</screen>
